version: '3'
services:
  emr-to-mozart-etl-mysql:
    image: edrisse/mozart-etl-mysql
    #build: mysql
    container_name: emr-to-mozart-etl-mysql
    volumes:
    - "./emr-to-mozart-etl-input:/openmrs-dump-to-import"
    networks:
    - emr-to-mozart-etl-network
  emr-to-mozart-etl-pdi:
    image: edrisse/mozart-etl-pdi
    #build: pdi
    container_name: emr-to-mozart-etl-pdi
    volumes:
    - "./emr-to-mozart-etl-output:/root/emr-data-migration"
    depends_on: 
    - emr-to-mozart-etl-mysql
    networks:
    - emr-to-mozart-etl-network
networks:
  emr-to-mozart-etl-network:

